/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingCompleteRouteImport } from './routes/booking-complete'
import { Route as BookRouteImport } from './routes/book'
import { Route as BaysRouteImport } from './routes/bays'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookWaiverRouteImport } from './routes/book.waiver'
import { Route as BookManualRouteImport } from './routes/book.manual'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCompleteRoute = BookingCompleteRouteImport.update({
  id: '/booking-complete',
  path: '/booking-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BaysRoute = BaysRouteImport.update({
  id: '/bays',
  path: '/bays',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const BookWaiverRoute = BookWaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => BookRoute,
} as any)
const BookManualRoute = BookManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => BookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/bays': typeof BaysRoute
  '/book': typeof BookRouteWithChildren
  '/booking-complete': typeof BookingCompleteRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/book/manual': typeof BookManualRoute
  '/book/waiver': typeof BookWaiverRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/bays': typeof BaysRoute
  '/booking-complete': typeof BookingCompleteRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/book/manual': typeof BookManualRoute
  '/book/waiver': typeof BookWaiverRoute
  '/book': typeof BookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/bays': typeof BaysRoute
  '/book': typeof BookRouteWithChildren
  '/booking-complete': typeof BookingCompleteRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/book/manual': typeof BookManualRoute
  '/book/waiver': typeof BookWaiverRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/bays'
    | '/book'
    | '/booking-complete'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-service'
    | '/book/manual'
    | '/book/waiver'
    | '/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/bays'
    | '/booking-complete'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-service'
    | '/book/manual'
    | '/book/waiver'
    | '/book'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/bays'
    | '/book'
    | '/booking-complete'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-service'
    | '/book/manual'
    | '/book/waiver'
    | '/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  BaysRoute: typeof BaysRoute
  BookRoute: typeof BookRouteWithChildren
  BookingCompleteRoute: typeof BookingCompleteRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-complete': {
      id: '/booking-complete'
      path: '/booking-complete'
      fullPath: '/booking-complete'
      preLoaderRoute: typeof BookingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bays': {
      id: '/bays'
      path: '/bays'
      fullPath: '/bays'
      preLoaderRoute: typeof BaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/waiver': {
      id: '/book/waiver'
      path: '/waiver'
      fullPath: '/book/waiver'
      preLoaderRoute: typeof BookWaiverRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/manual': {
      id: '/book/manual'
      path: '/manual'
      fullPath: '/book/manual'
      preLoaderRoute: typeof BookManualRouteImport
      parentRoute: typeof BookRoute
    }
  }
}

interface BookRouteChildren {
  BookManualRoute: typeof BookManualRoute
  BookWaiverRoute: typeof BookWaiverRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookManualRoute: BookManualRoute,
  BookWaiverRoute: BookWaiverRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  BaysRoute: BaysRoute,
  BookRoute: BookRouteWithChildren,
  BookingCompleteRoute: BookingCompleteRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
