/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BaysRouteImport } from './routes/bays'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookWaiverRouteImport } from './routes/book.waiver'
import { Route as BookScheduleRouteImport } from './routes/book.schedule'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BaysRoute = BaysRouteImport.update({
  id: '/bays',
  path: '/bays',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const BookWaiverRoute = BookWaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => BookRoute,
} as any)
const BookScheduleRoute = BookScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => BookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bays': typeof BaysRoute
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/book/schedule': typeof BookScheduleRoute
  '/book/waiver': typeof BookWaiverRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bays': typeof BaysRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/book/schedule': typeof BookScheduleRoute
  '/book/waiver': typeof BookWaiverRoute
  '/book': typeof BookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bays': typeof BaysRoute
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/book/schedule': typeof BookScheduleRoute
  '/book/waiver': typeof BookWaiverRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bays'
    | '/book'
    | '/contact'
    | '/services'
    | '/book/schedule'
    | '/book/waiver'
    | '/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bays'
    | '/contact'
    | '/services'
    | '/book/schedule'
    | '/book/waiver'
    | '/book'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bays'
    | '/book'
    | '/contact'
    | '/services'
    | '/book/schedule'
    | '/book/waiver'
    | '/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BaysRoute: typeof BaysRoute
  BookRoute: typeof BookRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bays': {
      id: '/bays'
      path: '/bays'
      fullPath: '/bays'
      preLoaderRoute: typeof BaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/waiver': {
      id: '/book/waiver'
      path: '/waiver'
      fullPath: '/book/waiver'
      preLoaderRoute: typeof BookWaiverRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/schedule': {
      id: '/book/schedule'
      path: '/schedule'
      fullPath: '/book/schedule'
      preLoaderRoute: typeof BookScheduleRouteImport
      parentRoute: typeof BookRoute
    }
  }
}

interface BookRouteChildren {
  BookScheduleRoute: typeof BookScheduleRoute
  BookWaiverRoute: typeof BookWaiverRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookScheduleRoute: BookScheduleRoute,
  BookWaiverRoute: BookWaiverRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BaysRoute: BaysRoute,
  BookRoute: BookRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
